In [161]:
import pandas as pd

In [162]:
# Lambda Test
lambda_test = lambda a,b: a + b
print(lambda_test(2,3))

5

In [163]:
data = {
    'A': [1,2,3,4],
    'B': [10,20,30,40]
}
df = pd.DataFrame(data)
df

   A   B
0  1  10
1  2  20
2  3  30
3  4  40

In [164]:
df['Sum'] = df.apply(lambda x: x['A'] + x['B'], axis=1) # .applay() has same func. as .iterrows()
df

   A   B  Sum
0  1  10   11
1  2  20   22
2  3  30   33
3  4  40   44

In [165]:
df = df.map(lambda x: x * 2) # Use the .applymap on python below 3.12
df

   A   B  Sum
0  2  20   22
1  4  40   44
2  6  60   66
3  8  80   88

In [166]:
df['Kat'] = df.apply(lambda x: 'Tinggi' if x['Sum'] >= 30 else 'Rendah', axis=1)
df

   A   B  Sum     Kat
0  2  20   22  Rendah
1  4  40   44  Tinggi
2  6  60   66  Tinggi
3  8  80   88  Tinggi

In [167]:
# Data baru
data = {
    'Nama': ['Masbro', 'MustANice', 'Poyopoyo'],
    'Umur': [20, 1000, 24],
    'Gaji': [1000000, 0, 5000]
}
df_dic = pd.DataFrame(data)
df_dic

        Nama  Umur     Gaji
0     Masbro    20  1000000
1  MustANice  1000        0
2   Poyopoyo    24     5000

In [168]:
def kat_umur(umur):
    if umur < 25 and umur >= 0:
        return "Muda"
    elif umur >= 25:
        return "Aku sudah kecewa"

df_dic['Kategori'] = df_dic['Umur'].apply(kat_umur)
df_dic

        Nama  Umur     Gaji          Kategori
0     Masbro    20  1000000              Muda
1  MustANice  1000        0  Aku sudah kecewa
2   Poyopoyo    24     5000              Muda

In [169]:
# REMEMBAH
# x['y']; x is rows, y is columns or value or whatever you wanna say it :v

# Alter way
def pajak(gaji, kategori):
    if kategori == "Muda":
        pajaks = gaji * 0.05
    else:
        pajaks = gaji * 0.1
    return pajaks

df_dic['Pajak_Alt'] = df_dic.apply(lambda x: pajak(x['Gaji'], x['Kategori']), axis=1)
df_dic

        Nama  Umur     Gaji          Kategori  Pajak_Alt
0     Masbro    20  1000000              Muda    50000.0
1  MustANice  1000        0  Aku sudah kecewa        0.0
2   Poyopoyo    24     5000              Muda      250.0

In [170]:
# Bonus dengan fungsi
def bonus_karyawan(x):
    bonus = x['Gaji']
    return bonus * 0.1

df_dic['Bonus'] = df_dic.apply(bonus_karyawan, axis=1)
df_dic

        Nama  Umur     Gaji          Kategori  Pajak_Alt     Bonus
0     Masbro    20  1000000              Muda    50000.0  100000.0
1  MustANice  1000        0  Aku sudah kecewa        0.0       0.0
2   Poyopoyo    24     5000              Muda      250.0     500.0

In [171]:
# Bonus dengan lambda
df_dic['Bonus'] = df_dic.apply(lambda x: x['Gaji'] * 0.1, axis=1)
df_dic

        Nama  Umur     Gaji          Kategori  Pajak_Alt     Bonus
0     Masbro    20  1000000              Muda    50000.0  100000.0
1  MustANice  1000        0  Aku sudah kecewa        0.0       0.0
2   Poyopoyo    24     5000              Muda      250.0     500.0

In [172]:
# Pajak dengan fungsi
def ppn(x):
    pajak= x['Gaji']
    kategori = x['Kategori']
    if kategori == "Muda":
        return pajak * 0.05
    else:
        return pajak * 0.1

df_dic['Pajak'] = df_dic.apply(ppn, axis=1)
df_dic

        Nama  Umur     Gaji          Kategori  Pajak_Alt     Bonus    Pajak
0     Masbro    20  1000000              Muda    50000.0  100000.0  50000.0
1  MustANice  1000        0  Aku sudah kecewa        0.0       0.0      0.0
2   Poyopoyo    24     5000              Muda      250.0     500.0    250.0

In [173]:
# Pajak dengan lambda
df_dic['Pajak'] = df_dic.apply(lambda x: x['Gaji'] * 0.05 if x['Kategori'] == "Muda" else x['Gaji'] * 0.1, axis=1)
df_dic

        Nama  Umur     Gaji          Kategori  Pajak_Alt     Bonus    Pajak
0     Masbro    20  1000000              Muda    50000.0  100000.0  50000.0
1  MustANice  1000        0  Aku sudah kecewa        0.0       0.0      0.0
2   Poyopoyo    24     5000              Muda      250.0     500.0    250.0